# Generated by Django 4.2.1 on 2023-06-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField()),
                ('category', models.CharField(choices=[('cleaning ', 'general cleaning'), ('gardening ', 'gardening Services '), ('dry cleaning', 'carpets and rugs')], max_length=22)),
                ('experience_years', models.IntegerField()),
                ('experience_details', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('my_users.customuser',),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('my_users.customuser',),
        ),
    ]
