# Generated by Django 4.2.1 on 2023-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0002_provider_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
