# Generated by Django 4.2.2 on 2023-06-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0003_alter_provider_age_alter_provider_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='category',
        ),
    ]
