# Generated by Django 4.2.2 on 2023-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0005_provider_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(default=123456789),
        ),
    ]
