# Generated by Django 4.2.2 on 2023-06-15 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_users', '0004_remove_provider_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='providerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Booking.providerschedule')),
            ],
        ),
        migrations.CreateModel(
            name='service_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='Booking.service_category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_as_provider', to='my_users.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_recipient', to='my_users.recipient')),
                ('service_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_as_provider', to='Booking.service_info')),
            ],
        ),
        migrations.AddField(
            model_name='providerschedule',
            name='TimeSlot',
            field=models.ManyToManyField(related_name='schedules', to='Booking.timeslot'),
        ),
        migrations.AddField(
            model_name='providerschedule',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='my_users.provider'),
        ),
    ]
