# Generated by Django 4.2.2 on 2023-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
