# Generated by Django 4.2.2 on 2023-06-16 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0004_remove_provider_category'),
        ('Booking', '0002_alter_service_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='my_users.recipient')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Booking.reservationinfo')),
            ],
        ),
    ]
