# Generated by Django 4.2.2 on 2023-06-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_service_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_info',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_domain', to='Booking.service_domain'),
        ),
    ]
