# Generated by Django 4.2.2 on 2023-06-25 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_service_info_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_info',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
